title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://lei0lei.github.io/rust-gh

enable_copy_code_button: true
callouts:
  highlight:
    title: tips
    color: yellow
  
  warning:
    title: warning
    color: red

  note:
    title: note
    color: blue
